### ISSUE TITLE
Uncaught 'TimerItem' object has no attribute 'json' exception sometimes stops Depicted

### ISSUE THREAD

**Issue by scrofts** [bslatkin/dpxdt#163] opened 2015-10-13 10:42 UTC
Couldn't reopen #65 myself. I'm still getting the same error when I leave the server running for any length of time:

	ERROR workers.py:504] Error in workflow=dpxdt.client.queue_worker.RemoteQueueWorkflow({args: ('capture', <class 'dpxdt.client.capture_worker.DoCaptureQueueWorkflow'>), root: True, interrupted: False, kwargs: {max_tasks: 5, wait_seconds: 3}})#139715014742544 from item=dpxdt.client.timer_worker.TimerItem({ready_time: 1444193644.233015, delay_seconds: 10, done: True, parent: dpxdt.client.queue_worker.RemoteQueueWorkflow#139715014742544})#139714952756112, error=None
	Traceback (most recent call last):
	  File "/home/stan/dpxdt/dpxdt/client/workers.py", line 492, in _progress_workflow
	    next_item = generator.send(item)
	  File "/home/stan/dpxdt/dpxdt/client/queue_worker.py", line 220, in run
	    if next_item.json:
	AttributeError: 'TimerItem' object has no attribute 'json'

**Comment by bslatkin** [comment] 2016-03-07 00:54
Dupe of #65

**Comment by bslatkin** [comment] 2016-03-07 00:54
Going to reopen 65

**Closed by bslatkin** 2016-03-07 00:54 UTC
