### ISSUE TITLE
sqlalchemy.exc.OperationalError 

### ISSUE THREAD

**Issue by bowlej** [bslatkin/dpxdt#128] opened 2015-02-06 16:39 UTC
Hi There, i have an issue on my set up whereby every time we reboot our server where dpxdt is installed we end up with what looks like a broken db. The only way we have managed to fix things so far is dropping the dpxtd db and that recreating it. 

The os on the server is:

Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-41-generic x86_64)

The db is sql lite.

I have attached the full error screen that is displayed.
![sql error for vd tool](https://cloud.githubusercontent.com/assets/4520618/6083170/9803b74a-ae1e-11e4-80f1-ff9689879665.png)

Any help would be much appreciated.

**Comment by bslatkin** [comment] 2015-02-11 08:22
That's frustrating! Sorry to hear it. I haven't seen this one before. How are you actually starting the dpxdt server process? What's the command you're running? I wonder if it may be a variation of this:

http://stackoverflow.com/questions/17440605/flask-sqlalchemy-no-such-table

**Comment by bowlej** [comment] 2015-02-16 10:32
Thanks for the response, i am running './run_combined.sh' to start the server process. I also see issue #83 quite often.

Its a great tool, but its a pain that we cant keep historical diffs due to having to delete the db whenever we reboot the server.

**Comment by thxmike** [comment] 2015-10-02 17:31
We experience this same issue, each time our server is rebooted. The database no longer exists, I end up having to recreate the db with the command server.db.create_all().

**Comment by bslatkin** [comment] 2015-10-05 01:22
Pretty sure this is a duplicate of #83

**Closed by bslatkin** 2015-10-05 01:22 UTC
Labels: duplicate
