### ISSUE TITLE
dpxdt deployment issues

### ISSUE THREAD

**Issue by charstarstars** [bslatkin/dpxdt#117] opened 2014-10-28 22:32 UTC
Hey there,

It looks like the Google Cloud console has changed quite a bit since the dpxdt README was written...

I'm having issues with getting dpxdt up and deployed.

In the Deployment section, a few issues (corresponding to the deployment steps in the readme):
1. there isn't a `google_sql.sh` file in the repo. Also creating a new project from the Cloud console doesn't have the same behavior as creating one through appengine.google.com (and so running `./appengine_deploy.sh` gives an error about not finding an application with the id specified)
2. I think you mean "APIs & auth > Credentials" instead of "API Access"
3. It's not "Service Account Name" in the new console, it's "App Engine service account" under the Permission tab; there's no "team member" selection / addition, although you _can_ add it as a User in the bucket permissions
4. (no issues here)
5. (see 1) after creating an app through appengine.google.com I was able to deploy
6. after deploy, the app returns a 500 response when trying to access /admin (or any other page)

Are there any suggestions for how to resolve this issue? 
Thanks!

**Comment by bslatkin** [comment] 2015-04-19 23:16
I'm fixing the App Engine deploy in #133 so I'm going to treat this bug as a dupe of that one.

**Closed by bslatkin** 2015-04-19 23:16 UTC
